name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd server  # Di chuyển vào thư mục server
          npm install

      - name: Deploy to Heroku
        run: |
          cd server  # Di chuyển vào thư mục server
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git main
